"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { scanMusicDirectory, sortTracks } = require("./track-library");

const ROOT_DIRECTORY = __dirname;
const MUSIC_DIRECTORY = path.join(ROOT_DIRECTORY, "usa-1");
const DIST_DIRECTORY = path.join(ROOT_DIRECTORY, "dist");
const FUNCTION_DIRECTORY = path.join(ROOT_DIRECTORY, "netlify", "functions");
const MANIFEST_PATH = path.join(FUNCTION_DIRECTORY, "tracks-manifest.mjs");

const APP_FILES = [
  { source: "musicplayer.html", destination: "index.html" },
  { source: "styles.css", destination: "styles.css" },
  { source: "musicplayer.js", destination: "musicplayer.js" },
];

async function copyAppFiles() {
  for (const file of APP_FILES) {
    await fs.promises.copyFile(
      path.join(ROOT_DIRECTORY, file.source),
      path.join(DIST_DIRECTORY, file.destination),
    );
  }
}

async function copyTracks(tracks) {
  for (const track of tracks) {
    const relativeParts = track.id.split("/");
    const sourcePath = path.join(ROOT_DIRECTORY, ...relativeParts);
    const destinationPath = path.join(DIST_DIRECTORY, ...relativeParts);

    await fs.promises.mkdir(path.dirname(destinationPath), { recursive: true });
    await fs.promises.copyFile(sourcePath, destinationPath);
  }
}

async function writeFunctionManifest(tracks) {
  await fs.promises.mkdir(FUNCTION_DIRECTORY, { recursive: true });

  const contents = [
    "// Generated by build.js. Do not edit this file manually.",
    `export const tracks = Object.freeze(${JSON.stringify(tracks, null, 2)});`,
    "",
  ].join("\n");

  await fs.promises.writeFile(MANIFEST_PATH, contents, "utf8");
}

async function build() {
  const tracks = sortTracks(await scanMusicDirectory(ROOT_DIRECTORY, MUSIC_DIRECTORY));

  if (tracks.length === 0) {
    throw new Error("No supported media files were found in usa-1.");
  }

  await fs.promises.rm(DIST_DIRECTORY, { recursive: true, force: true });
  await fs.promises.mkdir(DIST_DIRECTORY, { recursive: true });

  await copyAppFiles();
  await copyTracks(tracks);
  await writeFunctionManifest(tracks);

  console.log(`Built the Netlify site with ${tracks.length} tracks.`);
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
